version: "3.9"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu22.04
    volumes:
      - ../:/workspace:cached
    ports:
      - "8080:8080"
      - "5173:5173"
    command: /bin/sh -c "sleep infinity"
